WebApp_camera-laptop/Areas/Admin/Controllers/AdminProductCategorisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_camera_laptop.Models;

namespace WebApp_camera_laptop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductCategorisController : Controller
    {
        private readonly webap_camera_laptopContext _context;

        public AdminProductCategorisController(webap_camera_laptopContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminProductCategoris
        public async Task<IActionResult> Index()
        {
            try
            {
                var webap_camera_laptopContext = _context.ProductCategoris
                .Include(p => p.Cat)
                .Include(p => p.Products);
                ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName");
                ViewData["products"] = new SelectList(_context.Products, "ProductId", "ProductName");
                return View(await webap_camera_laptopContext.ToListAsync());
            }
            catch (Exception ex) {
                return View("Error");
            }
           
        }

        // GET: Admin/AdminProductCategoris/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategori = await _context.ProductCategoris
                .Include(p => p.Cat)
                .Include(p => p.Products)
                .FirstOrDefaultAsync(m => m.ProductCatId == id);
            if (productCategori == null)
            {
                return NotFound();
            }

            return View(productCategori);
        }

        // GET: Admin/AdminProductCategoris/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName");
            ViewData["ProductsId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View();
        }

        // POST: Admin/AdminProductCategoris/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductsId,CatId,ProductCatId")] ProductCategori productCategori)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productCategori);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", productCategori.CatId);
            ViewData["ProductsId"] = new SelectList(_context.Products, "ProductId", "ProductName", productCategori.ProductsId);
            return View(productCategori);
        }

        // GET: Admin/AdminProductCategoris/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategori = await _context.ProductCategoris.FindAsync(id);
            if (productCategori == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId", productCategori.CatId);
            ViewData["ProductsId"] = new SelectList(_context.Products, "ProductId", "ProductId", productCategori.ProductsId);
            return View(productCategori);
        }

        // POST: Admin/AdminProductCategoris/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductsId,CatId,ProductCatId")] ProductCategori productCategori)
        {
            if (id != productCategori.ProductCatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productCategori);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductCategoriExists(productCategori.ProductCatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId", productCategori.CatId);
            ViewData["ProductsId"] = new SelectList(_context.Products, "ProductId", "ProductId", productCategori.ProductsId);
            return View(productCategori);
        }

        // GET: Admin/AdminProductCategoris/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategori = await _context.ProductCategoris
                .Include(p => p.Cat)
                .Include(p => p.Products)
                .FirstOrDefaultAsync(m => m.ProductCatId == id);
            if (productCategori == null)
            {
                return NotFound();
            }

            return View(productCategori);
        }

        // POST: Admin/AdminProductCategoris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productCategori = await _context.ProductCategoris.FindAsync(id);
            _context.ProductCategoris.Remove(productCategori);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductCategoriExists(int id)
        {
            return _context.ProductCategoris.Any(e => e.ProductCatId == id);
        }
    }
}

WebApp_camera-laptop/Areas/Admin/Views/AdminProductCategoris/Create.cshtml
@model WebApp_camera_laptop.Models.ProductCategori

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý danh mục - sản phẩm</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Thêm danh mục - sản phẩm</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="emailfield">Chọn danh mục</label>
                <select class="form-control" asp-for="CatId" asp-items="ViewBag.CatId">
                    <option value="" disabled selected>Chọn danh mục</option>
                </select>
            </div>
            <div class="form-group ">
                <label for="emailfield">Chọn sản phẩm</label>
                <select class="form-control" asp-for="ProductsId" asp-items="ViewBag.ProductsId">
                    <option value="" disabled selected>Chọn sản phẩm</option>
                </select>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Tạo mới</button>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-default">Quay lại</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProductCategoris/Delete.cshtml
@model WebApp_camera_laptop.Models.ProductCategori

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductCategori</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cat.CatId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Products)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Products.ProductId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductCatId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProductCategoris/Details.cshtml
@model WebApp_camera_laptop.Models.ProductCategori

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProductCategori</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cat.CatId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Products)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Products.ProductId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductCatId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProductCategoris/Edit.cshtml
@model WebApp_camera_laptop.Models.ProductCategori

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

<h4>ProductCategori</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductsId" class="control-label"></label>
                <select asp-for="ProductsId" class="form-control" asp-items="ViewBag.ProductsId"></select>
                <span asp-validation-for="ProductsId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class="form-control" asp-items="ViewBag.CatId"></select>
                <span asp-validation-for="CatId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ProductCatId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProductCategoris/Index.cshtml
@model IEnumerable<WebApp_camera_laptop.Models.ProductCategori>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home">Trang chủ</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Quản lý danh mục - sản phẩm</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">Danh sách danh mục - sản phẩm</h4>
        <div class="dropdown js__drop_down">
            <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProductCategoris" asp-action="Create">Thêm danh mục - sản phẩm</a>
            <!-- /.sub-menu -->
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="col-1">ID</th>
                    <th scope="col" class="col-3">Tên danh mục</th>
                    <th scope="col" class="col-5">Tên sản phẩm</th>
                    <th scope="col" class="col-3">Hành động</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row" class="col-1">@item.ProductCatId</th>
                            <td class="col-3">@item.Cat.CatName</td>
                            <td class="col-5">@item.Products.ProductName</td>
                            <td class="col-3">
                                <div class="d-flex justify-content-between">
                                    <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProductCategoris" asp-action="Details" asp-route-id="@item.ProductCatId">Chi tiết</a>
                                    <a class="btn btn-primary btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProductCategoris" asp-action="Edit" asp-route-id="@item.ProductCatId">Cập nhật</a>
                                    <a class="btn btn-danger btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProductCategoris" asp-action="Delete" asp-route-id="@item.ProductCatId">Xóa</a>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <!-- /.box-content -->
</div>