WebApp_camera-laptop/Areas/Admin/Controllers/AdminNewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebApp_camera_laptop.Areas.Admin.ModelViews;
using WebApp_camera_laptop.Helpper;
using WebApp_camera_laptop.Models;

namespace WebApp_camera_laptop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminNewsController : Controller
    {
        private readonly webap_camera_laptopContext _context;
        public INotyfService _notyfService { get; }

        public AdminNewsController(webap_camera_laptopContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminNews
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var baiviet = _context.News
            .AsNoTracking()
            .Include(t => t.Cat);

            PagedList<News> models = new PagedList<News>(baiviet, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;

            return View(models);
        }

        // GET: Admin/AdminNews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.Account)
                .FirstOrDefaultAsync(m => m.NewId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: Admin/AdminNews/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.CategoriesNews, "CatNewId", "CatName");
            return View();
        }

        // POST: Admin/AdminNews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewsAdminViewModel baiviet, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (fThumb != null)
                    {
                        List<IFormFile> files = Request.Form.Files.ToList();
                        if (files != null && files.Count() < 2)
                        {
                            List<string> uploadedFileNames = new List<string>();
                            int imageIndex = 1;
                            foreach (var file in files)
                            {
                                string extension = Path.GetExtension(file.FileName);
                                string baseImageName = Utilities.SEOUrl(baiviet.Title);
                                string image = baseImageName + "_" + imageIndex.ToString() + extension;

                                string uploadedFileName = await Utilities.UploadFile(file, @"news", image);
                                uploadedFileNames.Add(uploadedFileName);
                                imageIndex++;
                            }
                            string thumbString = string.Join(",", uploadedFileNames);
                            baiviet.Thumb = thumbString;
                        }
                        else
                        {
                            _notyfService.Error("Không được thêm quá 1 tấm ảnh !!!");
                            return View(baiviet);
                        }

                    }
                    else
                    {
                        _notyfService.Error("Phải thêm tối thiểu 1 ảnh !!!");
                        return View(baiviet);
                    }
                    baiviet.Alias = Utilities.SEOUrl(baiviet.Title);
                    baiviet.CreatedDate = DateTime.Now;


                    News news = new News
                    {
                        Title = baiviet.Title,
                        Thumb = baiviet.Thumb,
                        Alias = baiviet.Alias,
                        CatId = baiviet.CatId,
                        CreatedDate = baiviet.CreatedDate,
                        Scontents = baiviet.Scontents,
                        Contents = baiviet.Contents,
                        IsHot = baiviet.IsHot,
                        IsNewfeed = baiviet.IsNewfeed,
                        Published = baiviet.Published,
                        Tags = baiviet.Tags,
                        MetaDesc = baiviet.MetaDesc,
                        MetaKey = baiviet.MetaKey,
 
                    };
                    _context.Add(news);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Tạo bài viết thành công");

                    // Sử dụng DbContext.Entry để lấy đối tượng sau khi đã thêm vào cơ sở dữ liệu
                    var addednews = _context.Entry(news).Entity;

                    
                    return RedirectToAction(nameof(Index));
                }
                ViewData["CatId"] = new SelectList(_context.CategoriesNews, "CatNewId", "CatName", baiviet.CatId);
                return View(baiviet);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        // GET: Admin/AdminNews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.CategoriesNews, "CatNewId", "CatName", news.CatId);
            return View(new NewsAdminViewModel
            {
                NewId = news.NewId,
                Title = news.Title,
                Alias = news.Alias,
                CatId = news.CatId,
                CreatedDate = news.CreatedDate,
                Scontents = news.Scontents,
                Contents = news.Contents,
                IsHot = (bool)news.IsHot,
                IsNewfeed = (bool)news.IsNewfeed,
                Published = (bool)news.Published,
                Tags = news.Tags,
                MetaDesc = news.MetaDesc,
                MetaKey = news.MetaKey
            });
        }

        // POST: Admin/AdminNews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NewsAdminViewModel baiviet)
        {
            if (id != baiviet.NewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingNews = await _context.News.FindAsync(baiviet.NewId);

                    if (existingNews == null)
                    {
                        return NotFound();
                    }
                    baiviet.Alias = Utilities.SEOUrl(baiviet.Title);
                    baiviet.CreatedDate = DateTime.Now;

                    existingNews.Title = baiviet.Title;
                    existingNews.Alias = baiviet.Alias;
                    existingNews.CatId = baiviet.CatId;
                    existingNews.CreatedDate = baiviet.CreatedDate;
                    existingNews.Scontents = baiviet.Scontents;
                    existingNews.Contents = baiviet.Contents;
                    existingNews.IsHot = baiviet.IsHot;
                    existingNews.IsNewfeed = baiviet.IsNewfeed;
                    existingNews.Published = baiviet.Published;
                    existingNews.Tags = baiviet.Tags;
                    existingNews.MetaDesc = baiviet.MetaDesc;
                    existingNews.MetaKey = baiviet.MetaKey;


                    _context.Update(existingNews);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật bài viết thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(baiviet.NewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.CategoriesNews, "CatNewId", "CatName", baiviet.CatId);
            return View(baiviet);
        }

        // GET: Admin/AdminNews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.Account)
                .FirstOrDefaultAsync(m => m.NewId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: Admin/AdminNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);

WebApp_camera-laptop/Areas/Admin/Views/AdminNews/Create.cshtml
@model WebApp_camera_laptop.Areas.Admin.ModelViews.NewsAdminViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/assets/admin/plugin/summernote/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/admin/plugin/summernote/css/summernote.min.css" rel="stylesheet">

}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý bài viết</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Thêm bài viết</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">Form nhập thông tin bài viết</h4>
        <!-- /.box-title -->
        <!-- /.dropdown js__dropdown -->
        <form asp-controller="AdminNews" asp-action="Create" method="post" enctype="multipart/form-data">
            <div id="tabsleft" class="tabbable tabs-left">
                <ul class="nav nav-tabs">
                    <li class="nav-item active"><a class="nav-link" href="#tabsleft-tab1" data-toggle="tab">Thông tin bài viết</a></li>
                    <li class="nav-item"><a class="nav-link" href="#tabsleft-tab2" data-toggle="tab">Nội dung bài viết</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tabsleft-tab1">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="emailfield">Tiêu đề bài viết</label>
                                <div class="controls">
                                    <input type="text" asp-for="Title" class="form-control">
                                    <span class="text-danger" asp-validation-for="Title"></span>
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="emailfield">Danh mục</label>
                                <select class="form-control select2_1" asp-for="CatId" asp-items="ViewBag.CatId">
                                </select>
                                <span class="text-danger" asp-validation-for="CatId"></span>

                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="emailfield">Mô tả ngắn bài viết</label>
                                <div class="controls">
                                    <textarea type="text" asp-for="Scontents" class="form-control"></textarea>
                                    <span class="text-danger" asp-validation-for="Scontents"></span>

                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Ảnh bìa</label>
                            <input type="file" multiple name="fThumb" asp-for="Thumb" />
                        </div>
                        <div class="form-group">
                            <div class="switch primary">
                                <input type="checkbox" asp-for="Published">
                                <label for="Published">Hoạt động</label>
                            </div>
                            <div class="switch primary">
                                <input type="checkbox" asp-for="IsNewfeed">
                                <label for="IsNewfeed">Hiển thị ở trang chủ</label>
                            </div>
                            <div class="switch primary">
                                <input type="checkbox" asp-for="IsHot">
                                <label for="IsHot">Bài viết nổi bật</label>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tabsleft-tab2">
                        <div class="card">
                            <div class="card-body">
                                <textarea class="summernote" asp-for="Contents"></textarea>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Tạo mới</button>
                <button asp-action="Index" class="btn btn-default">Quay lại</button>
            </div>
        </form>
    </div>

</div>

@section Scripts{
    <script src="~/assets/admin/plugin/summernote/js/jquery-3.5.1.min.js"></script>
    <script src="~/assets/admin/plugin/summernote/js/bootstrap.min.js"></script>
    <script src="~/assets/admin/plugin/summernote/js/summernote.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.summernote').summernote(
                {
                    height: 500,
                    toolbar: [

                        ['font', ['bold', 'italic', 'underline', 'clear']],
                        ['para', ['ul', 'ol']],
                        ['height', ['height']]
                        ['table', ['table']],
                        ['insert', ['link', 'picture', 'video']],
                        ['view', ['help']]
                    ],
                }
            );
        });
    </script>
   
}

WebApp_camera-laptop/Areas/Admin/Views/AdminNews/Delete.cshtml
@model WebApp_camera_laptop.Models.News

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Scontents)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Scontents)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CatId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CatId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsHot)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsHot)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsNewfeed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsNewfeed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Account.AccountId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NewId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminNews/Edit.cshtml
@model WebApp_camera_laptop.Areas.Admin.ModelViews.NewsAdminViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/assets/admin/plugin/summernote/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/admin/plugin/summernote/css/summernote.min.css" rel="stylesheet">


}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý bài viết</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Chỉnh sửa bài viết</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">Form chỉnh sửa bài viết</h4>
        <!-- /.box-title -->
        <!-- /.dropdown js__dropdown -->
        <form asp-controller="AdminNews" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="NewId" />
            <div id="tabsleft" class="tabbable tabs-left">
                <ul class="nav nav-tabs">
                    <li class="nav-item active"><a class="nav-link" href="#tabsleft-tab1" data-toggle="tab">Thông tin bài viết</a></li>
                    <li class="nav-item"><a class="nav-link" href="#tabsleft-tab2" data-toggle="tab">Nội dung bài viết</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tabsleft-tab1">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="emailfield">Tiêu đề bài viết</label>
                                <div class="controls">
                                    <input type="text" asp-for="Title" class="form-control">
                                    <span class="text-danger" asp-validation-for="Title"></span>
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="emailfield">Danh mục</label>
                                <select class="form-control select2_1" asp-for="CatId" asp-items="ViewBag.CatId">
                                </select>
                                <span class="text-danger" asp-validation-for="CatId"></span>

                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="emailfield">Mô tả ngắn bài viết</label>
                                <div class="controls">
                                    <textarea type="text" asp-for="Scontents" class="form-control"></textarea>
                                    <span class="text-danger" asp-validation-for="Scontents"></span>

                                </div>
                            </div>
                        </div>
                       @* <div class="form-group">
                            <label for="exampleInputFile">Ảnh bìa</label>
                            <input type="file" multiple name="fThumb" asp-for="Thumb" />
                        </div>*@
                        <div class="form-group">
                            <div class="switch primary">
                                <input type="checkbox" asp-for="Published">
                                <label for="Published">Hoạt động</label>
                            </div>
                            <div class="switch primary">
                                <input type="checkbox" asp-for="IsNewfeed">
                                <label for="IsNewfeed">Hiển thị ở trang chủ</label>
                            </div>
                            <div class="switch primary">
                                <input type="checkbox" asp-for="IsHot">
                                <label for="IsHot">Bài viết nổi bật</label>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tabsleft-tab2">
                        <div class="card">
                            <div class="card-body">
                                <textarea class="summernote" asp-for="Contents"></textarea>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Cập nhật</button>
                <button asp-action="Index" class="btn btn-default">Quay lại</button>
            </div>
        </form>
    </div>

</div>


@section Scripts{
    <script src="~/assets/admin/plugin/summernote/js/jquery-3.5.1.min.js"></script>
    <script src="~/assets/admin/plugin/summernote/js/bootstrap.min.js"></script>
    <script src="~/assets/admin/plugin/summernote/js/summernote.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.summernote').summernote(
                {
                    height: 500,
                    toolbar: [

                        ['font', ['bold', 'italic', 'underline', 'clear']],
                        ['para', ['ul', 'ol']],
                        ['height', ['height']]
                        ['table', ['table']],
                        ['insert', ['link', 'picture', 'video']],
                        ['view', ['help']]
                    ],
                }
            );
        });
    </script>
   
}

WebApp_camera-laptop/Areas/Admin/Views/AdminNews/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<WebApp_camera_laptop.Models.News>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<!-- breadcrumb area start -->
<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home">Trang chính</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Danh sách bài viết</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">Danh sách bài viết</h4>
        <div class="row">
            <div class="form-group col-md-4">
                <div class="form-group margin-bottom-20">
                    <select class="form-control" id="txtCatID" name="txtCatID" asp-items="ViewBag.DanhMuc">
                        <option value="" selected disabled>chọn danh mục</option>
                        <option value="0">chọn tất cả</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-4">
                @*<div class="input-group margin-bottom-20">
                    <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm sản phẩm">
                    <!-- /.input-group-btn -->
                </div>*@
            </div>
            <div class="form-group col-md-4">
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminNews" asp-action="Create">Thêm bài viết</a>
                    <!-- /.sub-menu -->
                </div>
            </div>
        </div>
        <!-- /.dropdown js__dropdown -->
        <table class="table table-striped table-bordered display">
            <thead>
                <tr>
                    <th>Tên bài viết</th>
                    <th>Danh mục</th>
                    <th>Ngày tạo</th>
                    <th>Trạng thái</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td width="300px">@item.Title</td>
                            <td>@item.Cat.CatName</td>
                            <td>@item.CreatedDate</td>
                            <td>
                                @if (item.Published != null && item.Published == true)
                                {
                                    <span class="notice notice-blue">Hoạt động</span>
                                }
                                else if (item.Published != null && item.Published == false)
                                {
                                    <span class="notice notice-danger">Khóa</span>
                                }
                                else
                                {
                                    <span class="notice notice-danger">Không có thông tin</span>

                                }
                            </td>
                            <td class="d-grid gap-2">
                                <div class="btn-group margin-top-10">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hành động <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        @*<li><a asp-area="Admin" asp-controller="AdminProducts" asp-action="Details" asp-route-id="@item.ProductId">Chi tiết</a></li>*@
                                        <li><a asp-area="Admin" asp-controller="AdminNews" asp-action="Edit" asp-route-id="@item.NewId">Chỉnh sửa</a></li>
                                        @* <li><a asp-area="Admin" asp-controller="AdminProducts" asp-action="Delete" asp-route-id="@item.ProductId">Xóa</a></li>*@
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-5">
                <div class="dataTables_info" id="example_info" role="status" aria-live="polite">Page @CurrentPage</div>
            </div>
            <div class="col-sm-7">
                <div class="dataTables_paginate paging_simple_numbers" id="example_paginate">
                    <ul class="pagination">
                        <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminNews" asp-action="Index"></pager>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-content -->
</div>