WebApp_camera-laptop/Areas/Admin/Controllers/AdminStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_camera_laptop.Models;

namespace WebApp_camera_laptop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminStatusController : Controller
    {
        private readonly webap_camera_laptopContext _context;

        public AdminStatusController(webap_camera_laptopContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminStatus
        public async Task<IActionResult> Index()
        {
            try {
            return View(await _context.Statuses.ToListAsync());
            }
            catch (Exception ex) { return View("Error"); }
        }

        // GET: Admin/AdminStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try {
                if (id == null)
                {
                    return NotFound();
                }

                var status = await _context.Statuses
                    .FirstOrDefaultAsync(m => m.StatusId == id);
                if (status == null)
                {
                    return NotFound();
                }

                return View(status);
            } catch (Exception ex) { return View("Error"); }
           
        }

        // GET: Admin/AdminStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StatusId,StatusName,Description")] Status status)
        {
            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Admin/AdminStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try {
                if (id == null)
                {
                    return NotFound();
                }

                var status = await _context.Statuses.FindAsync(id);
                if (status == null)
                {
                    return NotFound();
                }
                return View(status);
            } catch (Exception ex) { return View("Error"); }
           
        }

        // POST: Admin/AdminStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StatusId,StatusName,Description")] Status status)
        {
            if (id != status.StatusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.StatusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Admin/AdminStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.StatusId == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Admin/AdminStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var status = await _context.Statuses.FindAsync(id);
            _context.Statuses.Remove(status);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(int id)
        {
            return _context.Statuses.Any(e => e.StatusId == id);
        }
    }
}

WebApp_camera-laptop/Areas/Admin/Views/AdminStatus/Create.cshtml
@model WebApp_camera_laptop.Models.Status

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý trạng thái</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Thêm trạng thái</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tên trạng thái</label>
                <input asp-for="StatusName" class="form-control" />
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label"> Mô tả</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Tạo mới</button>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-default">Quay lại</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminStatus/Delete.cshtml
@model WebApp_camera_laptop.Models.Status

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Status</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StatusId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminStatus/Details.cshtml
@model WebApp_camera_laptop.Models.Status

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Status</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StatusId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminStatus/Edit.cshtml
@model WebApp_camera_laptop.Models.Status

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý trạng thái</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Cập nhật trạng thái</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StatusId" />
            <div class="form-group">
                <label class="control-label">Tên trạng thái</label>
                <input asp-for="StatusName" class="form-control" />
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label"> Mô tả</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Cập nhật</button>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-default">Quay lại</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminStatus/Index.cshtml
@model IEnumerable<WebApp_camera_laptop.Models.Status>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home">Trang chủ</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Quản lý trạng thái</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">Danh sách trạng thái</h4>
        <div class="dropdown js__drop_down">
            <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminStatus" asp-action="Create">Thêm trạng thái</a>
            <!-- /.sub-menu -->
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên trạng thái</th>
                    <th>Mô tả</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.StatusId</th>
                            <td>@item.StatusName</td>
                            <td>@item.Description</td>
                            <td>
                                <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminStatus" asp-action="Details" asp-route-id="@item.StatusId">Chi tiết</a>
                                <a class="btn btn-primary btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminStatus" asp-action="Edit" asp-route-id="@item.StatusId">Cập nhật</a>
                                <a class="btn btn-danger btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminStatus" asp-action="Delete" asp-route-id="@item.StatusId">Xóa</a>

                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
    <!-- /.box-content -->
</div>