WebApp_camera-laptop/Areas/Admin/Controllers/AdminProducersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_camera_laptop.Models;

namespace WebApp_camera_laptop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProducersController : Controller
    {
        private readonly webap_camera_laptopContext _context;

        public AdminProducersController(webap_camera_laptopContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminProducers
        public async Task<IActionResult> Index()
        {
            try {

            return View(await _context.Producers.ToListAsync());

            }
            catch (Exception ex) { return View("Error"); }
        }

        // GET: Admin/AdminProducers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try {
                if (id == null)
                {
                    return NotFound();
                }

                var producer = await _context.Producers
                    .FirstOrDefaultAsync(m => m.ProducerId == id);
                if (producer == null)
                {
                    return NotFound();
                }

                return View(producer);
            } catch (Exception) { return View("Error"); }
           
        }

        // GET: Admin/AdminProducers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminProducers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProducerId,ProducerName,Description,Thumb")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        // GET: Admin/AdminProducers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try {
                if (id == null)
                {
                    return NotFound();
                }

                var producer = await _context.Producers.FindAsync(id);
                if (producer == null)
                {
                    return NotFound();
                }
                return View(producer);
            } catch (Exception ex) { return View("Error"); }
           
        }

        // POST: Admin/AdminProducers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProducerId,ProducerName,Description,Thumb")] Producer producer)
        {
            if (id != producer.ProducerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProducerExists(producer.ProducerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        // GET: Admin/AdminProducers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producer = await _context.Producers
                .FirstOrDefaultAsync(m => m.ProducerId == id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // POST: Admin/AdminProducers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producer = await _context.Producers.FindAsync(id);
            _context.Producers.Remove(producer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProducerExists(int id)
        {
            return _context.Producers.Any(e => e.ProducerId == id);
        }
    }
}

WebApp_camera-laptop/Areas/Admin/Views/AdminProducers/Create.cshtml
@model WebApp_camera_laptop.Models.Producer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý nhà sản xuất</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Thêm nhà sản xuất</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  class="control-label">Tên nhà sản xuất</label>
                <input asp-for="ProducerName" class="form-control" />
                <span asp-validation-for="ProducerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label"> Mô tả</label>
                <textarea asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Tạo mới</button>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-default">Quay lại</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProducers/Delete.cshtml
@model WebApp_camera_laptop.Models.Producer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProducerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProducerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thumb)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProducerId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProducers/Details.cshtml
@model WebApp_camera_laptop.Models.Producer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý nhà bán hàng</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Thêm nhà bán hàng</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

<div>
    <h4>Producer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProducerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProducerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thumb)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProducerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProducers/Edit.cshtml
@model WebApp_camera_laptop.Models.Producer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="breadcrumb-item active"><a asp-action="Index">Quản lý nhà bán hàng</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Chỉnh sửa nhà bán hàng</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProducerId" />
            <div class="form-group">
                <label class="control-label">Tên nhà sản xuất</label>
                <input asp-for="ProducerName" class="form-control" />
                <span asp-validation-for="ProducerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label"> Mô tả</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Cập nhật</button>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-default">Quay lại</a>
</div>

WebApp_camera-laptop/Areas/Admin/Views/AdminProducers/Index.cshtml
@model IEnumerable<WebApp_camera_laptop.Models.Producer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="breadcrumb__area box-plr-75">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xxl-12">
                <div class="breadcrumb__wrapper">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home">Trang chủ</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a></a>Quản lý nhà sản xuất</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">Danh sách nhà sản xuất</h4>
        <div class="dropdown js__drop_down">
            <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProducers" asp-action="Create">Thêm nhà sản xuất</a>
            <!-- /.sub-menu -->
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên nhà sản xuất</th>
                    <th>Mô tả</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.ProducerId</th>
                            <td>@item.ProducerName</td>
                            <td>@item.Description</td>
                            <td>
                               @* <a class="btn btn-info btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProducers" asp-action="Details" asp-route-id="@item.ProducerId">Chi tiết</a>*@
                                <a class="btn btn-primary btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProducers" asp-action="Edit" asp-route-id="@item.ProducerId">Cập nhật</a>
                                @*<a class="btn btn-danger btn-xs waves-effect waves-light" asp-area="Admin" asp-controller="AdminProducers" asp-action="Delete" asp-route-id="@item.ProducerId">Xóa</a>*@

                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
    <!-- /.box-content -->
</div>